service: test-apiv1
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1
  memorySize: 1024
  timeout: 30

functions: 
  api: 
    handler: index.handler
    events:
      - httpApi: '*'

plugins: 
  - serverless-offline